"""Add pprtfolio schema

Revision ID: 688e67ff0950
Revises: ba5edb779f89
Create Date: 2024-03-12 18:34:27.169643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688e67ff0950'
down_revision: Union[str, None] = 'ba5edb779f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_portfolio', sa.Column('customer_first_name', sa.String(), nullable=True))
    op.add_column('tbl_portfolio', sa.Column('customer_last_name', sa.String(), nullable=True))
    op.add_column('tbl_portfolio', sa.Column('customer_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_portfolio', 'customer_email')
    op.drop_column('tbl_portfolio', 'customer_last_name')
    op.drop_column('tbl_portfolio', 'customer_first_name')
    # ### end Alembic commands ###
