"""Initial migration

Revision ID: 697eb5fbae76
Revises: 
Create Date: 2024-03-13 02:21:23.180860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '697eb5fbae76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_portfolio',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photographer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('university_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_first_name', sa.String(), nullable=True),
    sa.Column('customer_last_name', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photographer_id'], ['tbl_photographer.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['tbl_university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tbl_photo', 'tbl_portfolio', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_photo', type_='foreignkey')
    op.drop_table('tbl_portfolio')
    # ### end Alembic commands ###
