"""New Schema

Revision ID: 754cd5466c74
Revises: e1afc813d39f
Create Date: 2024-01-10 01:24:47.592167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754cd5466c74'
down_revision: Union[str, None] = 'e1afc813d39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_customer', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_customer', 'city')
    # ### end Alembic commands ###
