"""Add portfolio schema

Revision ID: 900cf57cb6e5
Revises: 688e67ff0950
Create Date: 2024-03-12 18:49:46.352688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900cf57cb6e5'
down_revision: Union[str, None] = '688e67ff0950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_portfolio', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.drop_column('tbl_portfolio', 'graduation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_portfolio', sa.Column('graduation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tbl_portfolio', 'graduation_year')
    # ### end Alembic commands ###
