"""Add stripe_id to product_type_table

Revision ID: 9522519bca68
Revises: dab1f44af225
Create Date: 2024-04-27 21:28:09.761251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9522519bca68'
down_revision: Union[str, None] = 'dab1f44af225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_product_type', sa.Column('stripe_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_product_type', 'stripe_id')
    # ### end Alembic commands ###
