"""Add pprtfolio schema

Revision ID: ba5edb779f89
Revises: 97195cbf735a
Create Date: 2024-03-12 18:00:32.127874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5edb779f89'
down_revision: Union[str, None] = '97195cbf735a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_portfolio', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_portfolio', 'is_active')
    # ### end Alembic commands ###
