"""Add product_type_id column to tbl_photo

Revision ID: dab1f44af225
Revises: 697eb5fbae76
Create Date: 2024-04-27 13:06:35.954506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dab1f44af225'
down_revision: Union[str, None] = '697eb5fbae76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_product_type',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tbl_photo', sa.Column('product_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'tbl_photo', 'tbl_product_type', ['product_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_photo', type_='foreignkey')
    op.drop_column('tbl_photo', 'product_type_id')
    op.drop_table('tbl_product_type')
    # ### end Alembic commands ###
